### ISSUE TITLE
Explanations below fields

### ISSUE THREAD

**Issue by TitaniaPorter** [UkuuLogic/ukuupeople-the-simple-crm#92]
Please say Enter Start Time and Enter End Time under the two boxes shown.

Also capitalize P in TouchPoint.

<img width="573" alt="enter time" src="https://cloud.githubusercontent.com/assets/25489988/24521598/50f6c4c6-1552-11e7-9199-61bd10ea4e7d.png">

**Comment by suniltorase** [comment]
Capitalization of letters is fixed in #102
Datetime is one field is generated by default by CMB2 plugin so we cannot separate the field. So to fulfill the above requirement I change the Start and End Date title from "Enter the Start Date" to "Enter the Start Date and Time" and "Enter the End Date" to "Enter the End Date and Time".
Related PR - #103
